
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action mediaPreviousAction;

	private global::Gtk.Action mediaStopAction;

	private global::Gtk.Action mediaPlayAction;

	private global::Gtk.Action mediaNextAction;

	private global::Gtk.Action newAction;

	private global::Gtk.Action openAction;

	private global::Gtk.Action floppyAction;

	private global::Gtk.Action revertToSavedAction;

	private global::Gtk.Action connectSerialAction;

	private global::Gtk.VBox VPanel1;

	private global::Gtk.HBox MenuBar;

	private global::Gtk.Toolbar MenuTools;

	private global::Gtk.ComboBox SerialPortDropdown;

	private global::Gtk.ComboBox BaudRateDropdown;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.Entry TimeEntry;

	private global::Gtk.Label label2;

	private global::Gtk.Toolbar MediaControls;

	private global::Gtk.HPaned HPanel1;

	private global::Gtk.VPaned vpaned1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TreeView FrameTreeView;

	private global::Gtk.VBox TerminalPanel;

	private global::Gtk.HBox TerminalHeader;

	private global::Gtk.Label label1;

	private global::Gtk.ScrolledWindow TerminalScrollWindow;

	private global::Gtk.TextView SerialTerminal;

	private global::Gtk.VBox vbox7;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Label label15;

	private global::Gtk.ScrolledWindow scrolledwindow1;

	private global::Gtk.VBox FramePropertiesPanel;

	private global::Gtk.VBox PropertyContainer1;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.VBox PropertyContent1;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label label13;

	private global::Gtk.Entry entry3;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Label label14;

	private global::Gtk.Entry entry4;

	private global::Gtk.VBox PropertyContainer;

	private global::Gtk.HSeparator hseparator2;

	private global::Gtk.HBox PropertyHeader;

	private global::Gtk.Label label4;

	private global::Gtk.VBox PropertyContent;

	private global::Gtk.HScale ActuatorScale;

	private global::Gtk.HScale ActuatorScale1;

	private global::Gtk.HScale ActuatorScale2;

	private global::Gtk.HScale ActuatorScale3;

	private global::Gtk.HScale ActuatorScale4;

	private global::Gtk.HScale ActuatorScale5;

	private global::Gtk.HScale ActuatorScale6;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.mediaPreviousAction = new global::Gtk.Action("mediaPreviousAction", null, null, "gtk-media-previous");
		w1.Add(this.mediaPreviousAction, null);
		this.mediaStopAction = new global::Gtk.Action("mediaStopAction", null, null, "gtk-media-stop");
		w1.Add(this.mediaStopAction, null);
		this.mediaPlayAction = new global::Gtk.Action("mediaPlayAction", null, null, "gtk-media-play");
		w1.Add(this.mediaPlayAction, null);
		this.mediaNextAction = new global::Gtk.Action("mediaNextAction", null, null, "gtk-media-next");
		w1.Add(this.mediaNextAction, null);
		this.newAction = new global::Gtk.Action("newAction", null, null, "gtk-new");
		w1.Add(this.newAction, null);
		this.openAction = new global::Gtk.Action("openAction", null, null, "gtk-open");
		w1.Add(this.openAction, null);
		this.floppyAction = new global::Gtk.Action("floppyAction", null, null, "gtk-floppy");
		w1.Add(this.floppyAction, null);
		this.revertToSavedAction = new global::Gtk.Action("revertToSavedAction", null, null, "gtk-revert-to-saved");
		w1.Add(this.revertToSavedAction, null);
		this.connectSerialAction = new global::Gtk.Action("connectSerialAction", null, null, "gtk-disconnect");
		w1.Add(this.connectSerialAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("RobotInterface");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.VPanel1 = new global::Gtk.VBox();
		this.VPanel1.Name = "VPanel1";
		this.VPanel1.Spacing = 6;
		// Container child VPanel1.Gtk.Box+BoxChild
		this.MenuBar = new global::Gtk.HBox();
		this.MenuBar.Name = "MenuBar";
		this.MenuBar.Spacing = 6;
		// Container child MenuBar.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><toolbar name='MenuTools'><toolitem name='newAction' action='newAction'/><separator/><toolitem name='openAction' action='openAction'/><separator/><toolitem name='floppyAction' action='floppyAction'/><toolitem name='revertToSavedAction' action='revertToSavedAction'/><separator/><toolitem name='connectSerialAction' action='connectSerialAction'/></toolbar></ui>");
		this.MenuTools = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/MenuTools")));
		this.MenuTools.Name = "MenuTools";
		this.MenuTools.ShowArrow = false;
		this.MenuTools.IconSize = ((global::Gtk.IconSize)(2));
		this.MenuBar.Add(this.MenuTools);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.MenuBar[this.MenuTools]));
		w2.Position = 0;
		w2.Expand = false;
		// Container child MenuBar.Gtk.Box+BoxChild
		this.SerialPortDropdown = global::Gtk.ComboBox.NewText();
		this.SerialPortDropdown.Name = "SerialPortDropdown";
		this.MenuBar.Add(this.SerialPortDropdown);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.MenuBar[this.SerialPortDropdown]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child MenuBar.Gtk.Box+BoxChild
		this.BaudRateDropdown = global::Gtk.ComboBox.NewText();
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("110"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("300"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("600"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("1200"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("2400"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("4800"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("9600"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("14400"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("19200"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("38400"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("57600"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("115200"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("128000"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("256000"));
		this.BaudRateDropdown.Name = "BaudRateDropdown";
		this.BaudRateDropdown.Active = 11;
		this.MenuBar.Add(this.BaudRateDropdown);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.MenuBar[this.BaudRateDropdown]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child MenuBar.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.MenuBar.Add(this.fixed1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.MenuBar[this.fixed1]));
		w5.PackType = ((global::Gtk.PackType)(1));
		w5.Position = 3;
		// Container child MenuBar.Gtk.Box+BoxChild
		this.TimeEntry = new global::Gtk.Entry();
		this.TimeEntry.WidthRequest = 160;
		this.TimeEntry.CanFocus = true;
		this.TimeEntry.Name = "TimeEntry";
		this.TimeEntry.IsEditable = true;
		this.TimeEntry.InvisibleChar = '•';
		this.MenuBar.Add(this.TimeEntry);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.MenuBar[this.TimeEntry]));
		w6.PackType = ((global::Gtk.PackType)(1));
		w6.Position = 4;
		w6.Expand = false;
		// Container child MenuBar.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Time (Milliseconds):");
		this.MenuBar.Add(this.label2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.MenuBar[this.label2]));
		w7.PackType = ((global::Gtk.PackType)(1));
		w7.Position = 5;
		w7.Expand = false;
		w7.Fill = false;
		// Container child MenuBar.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><toolbar name='MediaControls'><toolitem name='mediaPreviousAction' action='mediaPreviousAction'/><toolitem name='mediaStopAction' action='mediaStopAction'/><toolitem name='mediaPlayAction' action='mediaPlayAction'/><toolitem name='mediaNextAction' action='mediaNextAction'/></toolbar></ui>");
		this.MediaControls = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/MediaControls")));
		this.MediaControls.Name = "MediaControls";
		this.MediaControls.ShowArrow = false;
		this.MediaControls.IconSize = ((global::Gtk.IconSize)(2));
		this.MenuBar.Add(this.MediaControls);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.MenuBar[this.MediaControls]));
		w8.PackType = ((global::Gtk.PackType)(1));
		w8.Position = 6;
		w8.Expand = false;
		this.VPanel1.Add(this.MenuBar);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.VPanel1[this.MenuBar]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child VPanel1.Gtk.Box+BoxChild
		this.HPanel1 = new global::Gtk.HPaned();
		this.HPanel1.CanFocus = true;
		this.HPanel1.Name = "HPanel1";
		this.HPanel1.Position = 867;
		// Container child HPanel1.Gtk.Paned+PanedChild
		this.vpaned1 = new global::Gtk.VPaned();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 406;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.FrameTreeView = new global::Gtk.TreeView();
		this.FrameTreeView.CanFocus = true;
		this.FrameTreeView.Name = "FrameTreeView";
		this.GtkScrolledWindow1.Add(this.FrameTreeView);
		this.vpaned1.Add(this.GtkScrolledWindow1);
		global::Gtk.Paned.PanedChild w11 = ((global::Gtk.Paned.PanedChild)(this.vpaned1[this.GtkScrolledWindow1]));
		w11.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.TerminalPanel = new global::Gtk.VBox();
		this.TerminalPanel.Name = "TerminalPanel";
		this.TerminalPanel.Spacing = 6;
		// Container child TerminalPanel.Gtk.Box+BoxChild
		this.TerminalHeader = new global::Gtk.HBox();
		this.TerminalHeader.Name = "TerminalHeader";
		this.TerminalHeader.Spacing = 6;
		// Container child TerminalHeader.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Terminal");
		this.TerminalHeader.Add(this.label1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.TerminalHeader[this.label1]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		this.TerminalPanel.Add(this.TerminalHeader);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.TerminalPanel[this.TerminalHeader]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child TerminalPanel.Gtk.Box+BoxChild
		this.TerminalScrollWindow = new global::Gtk.ScrolledWindow();
		this.TerminalScrollWindow.Name = "TerminalScrollWindow";
		this.TerminalScrollWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child TerminalScrollWindow.Gtk.Container+ContainerChild
		this.SerialTerminal = new global::Gtk.TextView();
		this.SerialTerminal.CanFocus = true;
		this.SerialTerminal.Name = "SerialTerminal";
		this.SerialTerminal.Editable = false;
		this.SerialTerminal.CursorVisible = false;
		this.TerminalScrollWindow.Add(this.SerialTerminal);
		this.TerminalPanel.Add(this.TerminalScrollWindow);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.TerminalPanel[this.TerminalScrollWindow]));
		w15.Position = 1;
		this.vpaned1.Add(this.TerminalPanel);
		global::Gtk.Paned.PanedChild w16 = ((global::Gtk.Paned.PanedChild)(this.vpaned1[this.TerminalPanel]));
		w16.Resize = false;
		w16.Shrink = false;
		this.HPanel1.Add(this.vpaned1);
		global::Gtk.Paned.PanedChild w17 = ((global::Gtk.Paned.PanedChild)(this.HPanel1[this.vpaned1]));
		w17.Resize = false;
		// Container child HPanel1.Gtk.Paned+PanedChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label15 = new global::Gtk.Label();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Frame Properties");
		this.hbox7.Add(this.label15);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label15]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		this.vbox7.Add(this.hbox7);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox7]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		global::Gtk.Viewport w20 = new global::Gtk.Viewport();
		w20.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.FramePropertiesPanel = new global::Gtk.VBox();
		this.FramePropertiesPanel.Name = "FramePropertiesPanel";
		this.FramePropertiesPanel.Spacing = 6;
		// Container child FramePropertiesPanel.Gtk.Box+BoxChild
		this.PropertyContainer1 = new global::Gtk.VBox();
		this.PropertyContainer1.Name = "PropertyContainer1";
		this.PropertyContainer1.Spacing = 6;
		// Container child PropertyContainer1.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.PropertyContainer1.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.PropertyContainer1[this.hseparator1]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child PropertyContainer1.Gtk.Box+BoxChild
		this.PropertyContent1 = new global::Gtk.VBox();
		this.PropertyContent1.Name = "PropertyContent1";
		this.PropertyContent1.Spacing = 6;
		// Container child PropertyContent1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Name");
		this.hbox5.Add(this.label13);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label13]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		this.PropertyContent1.Add(this.hbox5);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.PropertyContent1[this.hbox5]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		// Container child PropertyContent1.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '•';
		this.PropertyContent1.Add(this.entry3);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.PropertyContent1[this.entry3]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		// Container child PropertyContent1.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Time (Milliseconds)");
		this.hbox6.Add(this.label14);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label14]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		this.PropertyContent1.Add(this.hbox6);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.PropertyContent1[this.hbox6]));
		w26.Position = 2;
		w26.Expand = false;
		w26.Fill = false;
		// Container child PropertyContent1.Gtk.Box+BoxChild
		this.entry4 = new global::Gtk.Entry();
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = true;
		this.entry4.InvisibleChar = '•';
		this.PropertyContent1.Add(this.entry4);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.PropertyContent1[this.entry4]));
		w27.Position = 3;
		w27.Expand = false;
		w27.Fill = false;
		this.PropertyContainer1.Add(this.PropertyContent1);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.PropertyContainer1[this.PropertyContent1]));
		w28.Position = 1;
		w28.Expand = false;
		w28.Fill = false;
		this.FramePropertiesPanel.Add(this.PropertyContainer1);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.FramePropertiesPanel[this.PropertyContainer1]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child FramePropertiesPanel.Gtk.Box+BoxChild
		this.PropertyContainer = new global::Gtk.VBox();
		this.PropertyContainer.Name = "PropertyContainer";
		this.PropertyContainer.Spacing = 6;
		// Container child PropertyContainer.Gtk.Box+BoxChild
		this.hseparator2 = new global::Gtk.HSeparator();
		this.hseparator2.Name = "hseparator2";
		this.PropertyContainer.Add(this.hseparator2);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.PropertyContainer[this.hseparator2]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		// Container child PropertyContainer.Gtk.Box+BoxChild
		this.PropertyHeader = new global::Gtk.HBox();
		this.PropertyHeader.Name = "PropertyHeader";
		this.PropertyHeader.Spacing = 6;
		// Container child PropertyHeader.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Actuators");
		this.PropertyHeader.Add(this.label4);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.PropertyHeader[this.label4]));
		w31.Position = 0;
		w31.Expand = false;
		w31.Fill = false;
		this.PropertyContainer.Add(this.PropertyHeader);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.PropertyContainer[this.PropertyHeader]));
		w32.Position = 1;
		w32.Expand = false;
		w32.Fill = false;
		// Container child PropertyContainer.Gtk.Box+BoxChild
		this.PropertyContent = new global::Gtk.VBox();
		this.PropertyContent.Name = "PropertyContent";
		this.PropertyContent.Spacing = 6;
		// Container child PropertyContent.Gtk.Box+BoxChild
		this.ActuatorScale = new global::Gtk.HScale(null);
		this.ActuatorScale.CanFocus = true;
		this.ActuatorScale.Name = "ActuatorScale";
		this.ActuatorScale.Adjustment.Upper = 180D;
		this.ActuatorScale.Adjustment.PageIncrement = 10D;
		this.ActuatorScale.Adjustment.StepIncrement = 1D;
		this.ActuatorScale.DrawValue = true;
		this.ActuatorScale.Digits = 0;
		this.ActuatorScale.ValuePos = ((global::Gtk.PositionType)(2));
		this.PropertyContent.Add(this.ActuatorScale);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.PropertyContent[this.ActuatorScale]));
		w33.Position = 0;
		w33.Expand = false;
		w33.Fill = false;
		// Container child PropertyContent.Gtk.Box+BoxChild
		this.ActuatorScale1 = new global::Gtk.HScale(null);
		this.ActuatorScale1.CanFocus = true;
		this.ActuatorScale1.Name = "ActuatorScale1";
		this.ActuatorScale1.Adjustment.Upper = 180D;
		this.ActuatorScale1.Adjustment.PageIncrement = 10D;
		this.ActuatorScale1.Adjustment.StepIncrement = 1D;
		this.ActuatorScale1.DrawValue = true;
		this.ActuatorScale1.Digits = 0;
		this.ActuatorScale1.ValuePos = ((global::Gtk.PositionType)(2));
		this.PropertyContent.Add(this.ActuatorScale1);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.PropertyContent[this.ActuatorScale1]));
		w34.Position = 1;
		w34.Expand = false;
		w34.Fill = false;
		// Container child PropertyContent.Gtk.Box+BoxChild
		this.ActuatorScale2 = new global::Gtk.HScale(null);
		this.ActuatorScale2.CanFocus = true;
		this.ActuatorScale2.Name = "ActuatorScale2";
		this.ActuatorScale2.Adjustment.Upper = 180D;
		this.ActuatorScale2.Adjustment.PageIncrement = 10D;
		this.ActuatorScale2.Adjustment.StepIncrement = 1D;
		this.ActuatorScale2.DrawValue = true;
		this.ActuatorScale2.Digits = 0;
		this.ActuatorScale2.ValuePos = ((global::Gtk.PositionType)(2));
		this.PropertyContent.Add(this.ActuatorScale2);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.PropertyContent[this.ActuatorScale2]));
		w35.Position = 2;
		w35.Expand = false;
		w35.Fill = false;
		// Container child PropertyContent.Gtk.Box+BoxChild
		this.ActuatorScale3 = new global::Gtk.HScale(null);
		this.ActuatorScale3.CanFocus = true;
		this.ActuatorScale3.Name = "ActuatorScale3";
		this.ActuatorScale3.Adjustment.Upper = 180D;
		this.ActuatorScale3.Adjustment.PageIncrement = 10D;
		this.ActuatorScale3.Adjustment.StepIncrement = 1D;
		this.ActuatorScale3.DrawValue = true;
		this.ActuatorScale3.Digits = 0;
		this.ActuatorScale3.ValuePos = ((global::Gtk.PositionType)(2));
		this.PropertyContent.Add(this.ActuatorScale3);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.PropertyContent[this.ActuatorScale3]));
		w36.Position = 3;
		w36.Expand = false;
		w36.Fill = false;
		// Container child PropertyContent.Gtk.Box+BoxChild
		this.ActuatorScale4 = new global::Gtk.HScale(null);
		this.ActuatorScale4.CanFocus = true;
		this.ActuatorScale4.Name = "ActuatorScale4";
		this.ActuatorScale4.Adjustment.Upper = 180D;
		this.ActuatorScale4.Adjustment.PageIncrement = 10D;
		this.ActuatorScale4.Adjustment.StepIncrement = 1D;
		this.ActuatorScale4.DrawValue = true;
		this.ActuatorScale4.Digits = 0;
		this.ActuatorScale4.ValuePos = ((global::Gtk.PositionType)(2));
		this.PropertyContent.Add(this.ActuatorScale4);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.PropertyContent[this.ActuatorScale4]));
		w37.Position = 4;
		w37.Expand = false;
		w37.Fill = false;
		// Container child PropertyContent.Gtk.Box+BoxChild
		this.ActuatorScale5 = new global::Gtk.HScale(null);
		this.ActuatorScale5.CanFocus = true;
		this.ActuatorScale5.Name = "ActuatorScale5";
		this.ActuatorScale5.Adjustment.Upper = 180D;
		this.ActuatorScale5.Adjustment.PageIncrement = 10D;
		this.ActuatorScale5.Adjustment.StepIncrement = 1D;
		this.ActuatorScale5.DrawValue = true;
		this.ActuatorScale5.Digits = 0;
		this.ActuatorScale5.ValuePos = ((global::Gtk.PositionType)(2));
		this.PropertyContent.Add(this.ActuatorScale5);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.PropertyContent[this.ActuatorScale5]));
		w38.Position = 5;
		w38.Expand = false;
		w38.Fill = false;
		// Container child PropertyContent.Gtk.Box+BoxChild
		this.ActuatorScale6 = new global::Gtk.HScale(null);
		this.ActuatorScale6.CanFocus = true;
		this.ActuatorScale6.Name = "ActuatorScale6";
		this.ActuatorScale6.Adjustment.Upper = 180D;
		this.ActuatorScale6.Adjustment.PageIncrement = 10D;
		this.ActuatorScale6.Adjustment.StepIncrement = 1D;
		this.ActuatorScale6.DrawValue = true;
		this.ActuatorScale6.Digits = 0;
		this.ActuatorScale6.ValuePos = ((global::Gtk.PositionType)(2));
		this.PropertyContent.Add(this.ActuatorScale6);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.PropertyContent[this.ActuatorScale6]));
		w39.Position = 6;
		w39.Expand = false;
		w39.Fill = false;
		this.PropertyContainer.Add(this.PropertyContent);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.PropertyContainer[this.PropertyContent]));
		w40.Position = 2;
		w40.Expand = false;
		w40.Fill = false;
		this.FramePropertiesPanel.Add(this.PropertyContainer);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.FramePropertiesPanel[this.PropertyContainer]));
		w41.Position = 1;
		w41.Expand = false;
		w41.Fill = false;
		w20.Add(this.FramePropertiesPanel);
		this.scrolledwindow1.Add(w20);
		this.vbox7.Add(this.scrolledwindow1);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.scrolledwindow1]));
		w44.Position = 1;
		this.HPanel1.Add(this.vbox7);
		global::Gtk.Paned.PanedChild w45 = ((global::Gtk.Paned.PanedChild)(this.HPanel1[this.vbox7]));
		w45.Resize = false;
		w45.Shrink = false;
		this.VPanel1.Add(this.HPanel1);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.VPanel1[this.HPanel1]));
		w46.Position = 1;
		this.Add(this.VPanel1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1127;
		this.DefaultHeight = 648;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.connectSerialAction.Activated += new global::System.EventHandler(this.OnConnectSerialActivated);
		this.SerialPortDropdown.Changed += new global::System.EventHandler(this.OnSerialPortDropdownChanged);
		this.BaudRateDropdown.Changed += new global::System.EventHandler(this.OnBaudRateDropdownChanged);
		this.ActuatorScale.ValueChanged += new global::System.EventHandler(this.OnActuatorScaleChanged);
		this.ActuatorScale1.ValueChanged += new global::System.EventHandler(this.OnActuatorScaleChanged);
		this.ActuatorScale2.ValueChanged += new global::System.EventHandler(this.OnActuatorScaleChanged);
		this.ActuatorScale3.ValueChanged += new global::System.EventHandler(this.OnActuatorScaleChanged);
		this.ActuatorScale4.ValueChanged += new global::System.EventHandler(this.OnActuatorScaleChanged);
		this.ActuatorScale5.ValueChanged += new global::System.EventHandler(this.OnActuatorScaleChanged);
		this.ActuatorScale6.ValueChanged += new global::System.EventHandler(this.OnActuatorScaleChanged);
	}
}
