
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action mediaPreviousAction;

	private global::Gtk.Action mediaStopAction;

	private global::Gtk.Action mediaPlayAction;

	private global::Gtk.Action mediaNextAction;

	private global::Gtk.Action newAction;

	private global::Gtk.Action openAction;

	private global::Gtk.Action floppyAction;

	private global::Gtk.Action revertToSavedAction;

	private global::Gtk.Action connectSerialAction;

	private global::Gtk.VBox VPanel1;

	private global::Gtk.HBox MenuBar;

	private global::Gtk.Toolbar MenuTools;

	private global::Gtk.ComboBox SerialPortDropdown;

	private global::Gtk.ComboBox BaudRateDropdown;

	private global::Gtk.VPaned VPanel2;

	private global::Gtk.HPaned HPanel1;

	private global::Gtk.Image image1;

	private global::Gtk.VBox ActuatorPanel;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label Label1;

	private global::Gtk.Button button2;

	private global::Gtk.ScrolledWindow ActuatorsList;

	private global::Gtk.VBox TimelinePanel;

	private global::Gtk.HBox ControlsPanel;

	private global::Gtk.Fixed SpaceLeft;

	private global::Gtk.Toolbar Controls;

	private global::Gtk.Fixed SpaceRight;

	private global::Gtk.ScrolledWindow SequencePanel;

	private global::Gtk.HPaned TimelineBox;

	private global::Gtk.Fixed fixed4;

	private global::Gtk.ScrolledWindow SequenceList;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.mediaPreviousAction = new global::Gtk.Action("mediaPreviousAction", null, null, "gtk-media-previous");
		w1.Add(this.mediaPreviousAction, null);
		this.mediaStopAction = new global::Gtk.Action("mediaStopAction", null, null, "gtk-media-stop");
		w1.Add(this.mediaStopAction, null);
		this.mediaPlayAction = new global::Gtk.Action("mediaPlayAction", null, null, "gtk-media-play");
		w1.Add(this.mediaPlayAction, null);
		this.mediaNextAction = new global::Gtk.Action("mediaNextAction", null, null, "gtk-media-next");
		w1.Add(this.mediaNextAction, null);
		this.newAction = new global::Gtk.Action("newAction", null, null, "gtk-new");
		w1.Add(this.newAction, null);
		this.openAction = new global::Gtk.Action("openAction", null, null, "gtk-open");
		w1.Add(this.openAction, null);
		this.floppyAction = new global::Gtk.Action("floppyAction", null, null, "gtk-floppy");
		w1.Add(this.floppyAction, null);
		this.revertToSavedAction = new global::Gtk.Action("revertToSavedAction", null, null, "gtk-revert-to-saved");
		w1.Add(this.revertToSavedAction, null);
		this.connectSerialAction = new global::Gtk.Action("connectSerialAction", null, null, "gtk-disconnect");
		w1.Add(this.connectSerialAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("RobotInterface");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.VPanel1 = new global::Gtk.VBox();
		this.VPanel1.Name = "VPanel1";
		this.VPanel1.Spacing = 6;
		// Container child VPanel1.Gtk.Box+BoxChild
		this.MenuBar = new global::Gtk.HBox();
		this.MenuBar.Name = "MenuBar";
		this.MenuBar.Spacing = 6;
		// Container child MenuBar.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><toolbar name='MenuTools'><toolitem name='newAction' action='newAction'/><separator/><toolitem name='openAction' action='openAction'/><separator/><toolitem name='floppyAction' action='floppyAction'/><toolitem name='revertToSavedAction' action='revertToSavedAction'/><separator/><toolitem name='connectSerialAction' action='connectSerialAction'/></toolbar></ui>");
		this.MenuTools = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/MenuTools")));
		this.MenuTools.Name = "MenuTools";
		this.MenuTools.ShowArrow = false;
		this.MenuTools.IconSize = ((global::Gtk.IconSize)(2));
		this.MenuBar.Add(this.MenuTools);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.MenuBar[this.MenuTools]));
		w2.Position = 0;
		w2.Expand = false;
		// Container child MenuBar.Gtk.Box+BoxChild
		this.SerialPortDropdown = global::Gtk.ComboBox.NewText();
		this.SerialPortDropdown.Name = "SerialPortDropdown";
		this.MenuBar.Add(this.SerialPortDropdown);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.MenuBar[this.SerialPortDropdown]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child MenuBar.Gtk.Box+BoxChild
		this.BaudRateDropdown = global::Gtk.ComboBox.NewText();
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("110"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("300"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("600"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("1200"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("2400"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("4800"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("9600"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("14400"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("19200"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("38400"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("57600"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("115200"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("128000"));
		this.BaudRateDropdown.AppendText(global::Mono.Unix.Catalog.GetString("256000"));
		this.BaudRateDropdown.Name = "BaudRateDropdown";
		this.BaudRateDropdown.Active = 11;
		this.MenuBar.Add(this.BaudRateDropdown);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.MenuBar[this.BaudRateDropdown]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.VPanel1.Add(this.MenuBar);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.VPanel1[this.MenuBar]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child VPanel1.Gtk.Box+BoxChild
		this.VPanel2 = new global::Gtk.VPaned();
		this.VPanel2.CanFocus = true;
		this.VPanel2.Name = "VPanel2";
		this.VPanel2.Position = 391;
		// Container child VPanel2.Gtk.Paned+PanedChild
		this.HPanel1 = new global::Gtk.HPaned();
		this.HPanel1.CanFocus = true;
		this.HPanel1.Name = "HPanel1";
		this.HPanel1.Position = 867;
		// Container child HPanel1.Gtk.Paned+PanedChild
		this.image1 = new global::Gtk.Image();
		this.image1.Name = "image1";
		this.HPanel1.Add(this.image1);
		global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.HPanel1[this.image1]));
		w6.Resize = false;
		// Container child HPanel1.Gtk.Paned+PanedChild
		this.ActuatorPanel = new global::Gtk.VBox();
		this.ActuatorPanel.Name = "ActuatorPanel";
		this.ActuatorPanel.Spacing = 6;
		// Container child ActuatorPanel.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.Label1 = new global::Gtk.Label();
		this.Label1.Name = "Label1";
		this.Label1.LabelProp = global::Mono.Unix.Catalog.GetString("Actuators");
		this.hbox2.Add(this.Label1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.Label1]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseStock = true;
		this.button2.UseUnderline = true;
		this.button2.Label = "gtk-add";
		this.hbox2.Add(this.button2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button2]));
		w8.PackType = ((global::Gtk.PackType)(1));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.ActuatorPanel.Add(this.hbox2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.ActuatorPanel[this.hbox2]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child ActuatorPanel.Gtk.Box+BoxChild
		this.ActuatorsList = new global::Gtk.ScrolledWindow();
		this.ActuatorsList.CanFocus = true;
		this.ActuatorsList.Name = "ActuatorsList";
		this.ActuatorsList.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
		this.ActuatorsList.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.ActuatorsList.ShadowType = ((global::Gtk.ShadowType)(1));
		this.ActuatorPanel.Add(this.ActuatorsList);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.ActuatorPanel[this.ActuatorsList]));
		w10.Position = 1;
		this.HPanel1.Add(this.ActuatorPanel);
		global::Gtk.Paned.PanedChild w11 = ((global::Gtk.Paned.PanedChild)(this.HPanel1[this.ActuatorPanel]));
		w11.Resize = false;
		this.VPanel2.Add(this.HPanel1);
		global::Gtk.Paned.PanedChild w12 = ((global::Gtk.Paned.PanedChild)(this.VPanel2[this.HPanel1]));
		w12.Resize = false;
		// Container child VPanel2.Gtk.Paned+PanedChild
		this.TimelinePanel = new global::Gtk.VBox();
		this.TimelinePanel.Name = "TimelinePanel";
		this.TimelinePanel.Spacing = 6;
		// Container child TimelinePanel.Gtk.Box+BoxChild
		this.ControlsPanel = new global::Gtk.HBox();
		this.ControlsPanel.Name = "ControlsPanel";
		this.ControlsPanel.Spacing = 6;
		// Container child ControlsPanel.Gtk.Box+BoxChild
		this.SpaceLeft = new global::Gtk.Fixed();
		this.SpaceLeft.Name = "SpaceLeft";
		this.SpaceLeft.HasWindow = false;
		this.ControlsPanel.Add(this.SpaceLeft);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.ControlsPanel[this.SpaceLeft]));
		w13.Position = 0;
		// Container child ControlsPanel.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><toolbar name='Controls'><toolitem name='mediaPreviousAction' action='mediaPreviousAction'/><toolitem name='mediaStopAction' action='mediaStopAction'/><toolitem name='mediaPlayAction' action='mediaPlayAction'/><toolitem name='mediaNextAction' action='mediaNextAction'/></toolbar></ui>");
		this.Controls = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/Controls")));
		this.Controls.Name = "Controls";
		this.Controls.ShowArrow = false;
		this.Controls.IconSize = ((global::Gtk.IconSize)(2));
		this.ControlsPanel.Add(this.Controls);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.ControlsPanel[this.Controls]));
		w14.Position = 1;
		w14.Expand = false;
		// Container child ControlsPanel.Gtk.Box+BoxChild
		this.SpaceRight = new global::Gtk.Fixed();
		this.SpaceRight.Name = "SpaceRight";
		this.SpaceRight.HasWindow = false;
		this.ControlsPanel.Add(this.SpaceRight);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.ControlsPanel[this.SpaceRight]));
		w15.Position = 2;
		this.TimelinePanel.Add(this.ControlsPanel);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.TimelinePanel[this.ControlsPanel]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child TimelinePanel.Gtk.Box+BoxChild
		this.SequencePanel = new global::Gtk.ScrolledWindow();
		this.SequencePanel.CanFocus = true;
		this.SequencePanel.Name = "SequencePanel";
		this.SequencePanel.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
		this.SequencePanel.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.SequencePanel.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child SequencePanel.Gtk.Container+ContainerChild
		global::Gtk.Viewport w17 = new global::Gtk.Viewport();
		w17.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.TimelineBox = new global::Gtk.HPaned();
		this.TimelineBox.CanFocus = true;
		this.TimelineBox.Name = "TimelineBox";
		this.TimelineBox.Position = 237;
		// Container child TimelineBox.Gtk.Paned+PanedChild
		this.fixed4 = new global::Gtk.Fixed();
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		this.TimelineBox.Add(this.fixed4);
		global::Gtk.Paned.PanedChild w18 = ((global::Gtk.Paned.PanedChild)(this.TimelineBox[this.fixed4]));
		w18.Resize = false;
		// Container child TimelineBox.Gtk.Paned+PanedChild
		this.SequenceList = new global::Gtk.ScrolledWindow();
		this.SequenceList.CanFocus = true;
		this.SequenceList.Name = "SequenceList";
		this.SequenceList.VscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.SequenceList.HscrollbarPolicy = ((global::Gtk.PolicyType)(0));
		this.SequenceList.ShadowType = ((global::Gtk.ShadowType)(1));
		this.TimelineBox.Add(this.SequenceList);
		w17.Add(this.TimelineBox);
		this.SequencePanel.Add(w17);
		this.TimelinePanel.Add(this.SequencePanel);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.TimelinePanel[this.SequencePanel]));
		w22.Position = 1;
		this.VPanel2.Add(this.TimelinePanel);
		global::Gtk.Paned.PanedChild w23 = ((global::Gtk.Paned.PanedChild)(this.VPanel2[this.TimelinePanel]));
		w23.Resize = false;
		w23.Shrink = false;
		this.VPanel1.Add(this.VPanel2);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.VPanel1[this.VPanel2]));
		w24.Position = 1;
		this.Add(this.VPanel1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1127;
		this.DefaultHeight = 648;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.connectSerialAction.Activated += new global::System.EventHandler(this.OnConnectSerialActivated);
		this.SerialPortDropdown.Changed += new global::System.EventHandler(this.OnSerialPortDropdownChanged);
		this.BaudRateDropdown.Changed += new global::System.EventHandler(this.OnBaudRateDropdownChanged);
	}
}
